baseURL = "https://blog.huszcza.dev"
languageCode = "en-us"
title = "Benedykt Huszcza"

defaultContentLanguage = "en"

hasCJKLanguage = false

disqusShortname = "Benedykt Huszcza"

[pagination]
pagerSize = 5

[build]
timeout = "600s"
