baseURL = "https://blog.huszcza.dev"
languageCode = "en-us"
title = "Benedykt Huszcza | Blog"

defaultContentLanguage = "en"
timeout = 60000
hasCJKLanguage = false

disqusShortname = "Benedykt Huszcza"

[pagination]
pagerSize = 5

[build]
timeout = "60s"
