[en]
languageName = "English"
languagedirection = "ltr"
title = "Benedykt Huszcza | Blog"
weight = 1

[pl]
languageName = "Polski"
languagedirection = "ltr"
title = "Benedykt Huszcza | Blog"
weight = 2
