name: Deploy Frontend to Mikrus

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd benedykt-the-dev/frontend
            git pull origin main
            docker build -t frontend-image:latest ./frontend
            docker stop my-frontend-container || true
            docker rm my-frontend-container || true
            docker run -d -p 3000:3000 --name my-frontend-container frontend-image:latest