name: Deploy Frontend to Mikrus

on:
  push:
    branches:
      - main
    paths:
      - 'blog/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 10344
          script: |
            cd benedykt-the-dev/blog 
            git pull origin main
            cd ../../huszcza-infra
            docker compose build blog
            docker-compose up -d blog